//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebShopEntities : DbContext
    {
        public WebShopEntities()
            : base("name=WebShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_customers> tbl_customers { get; set; }
        public virtual DbSet<tbl_orders> tbl_orders { get; set; }
        public virtual DbSet<tbl_product_categories> tbl_product_categories { get; set; }
        public virtual DbSet<tbl_products> tbl_products { get; set; }
        public virtual DbSet<tbl_relationship_op> tbl_relationship_op { get; set; }
        public virtual DbSet<tbl_relationship_pc> tbl_relationship_pc { get; set; }
    }
}
