//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_relationship_op = new HashSet<tbl_relationship_op>();
            this.tbl_relationship_pc = new HashSet<tbl_relationship_pc>();
        }
    
        public int[] ids_product_categories { get; set; }
        public int id_product { get; set; }
        public string number { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_relationship_op> tbl_relationship_op { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_relationship_pc> tbl_relationship_pc { get; set; }
    }
}
