//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_orders()
        {
            this.tbl_relationship_op = new HashSet<tbl_relationship_op>();
        }
    
        public int id_order { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    
        public virtual tbl_customers tbl_customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_relationship_op> tbl_relationship_op { get; set; }
    }
}
